#!/usr/bin/env python3
"""
Independent re-enumeration, in Python, of every structure classified in the
paper -- and a comparison of the result with the published CSV files.

Why this exists
---------------
`verify.py` answers the question "is everything in the published list correct,
canonical and pairwise non-isomorphic?".  It does NOT answer "is the published
list complete?", because it only ever looks at structures that are already in
the files.  This script answers the second question: it rebuilds every labelled
structure of order 3 and 4 from the axioms, with no reference to the CSV files
and no code shared with `src/enumerate.cpp`, and then checks the two lists
against each other in BOTH directions:

    * every structure this script generates appears in the published list, and
    * every structure in the published list is generated by this script.

Together with `verify.py` that settles correctness and completeness.

The only shortcut taken is Lemma 3.1 of the paper (0 lies in x+y precisely when
y = -x), which is used purely to cut the search space; it is proved in the
paper and re-proved, as a check, at the end of this file.

Run:  python3 enumerate_independently.py            (both orders)
      python3 enumerate_independently.py --order 4  (one order)

Runtime is about half a minute for both orders together on an ordinary laptop;
the C++ enumerator does the same work in about a second, which is the only
reason it exists.
"""
import argparse
import csv
import itertools
import os
import sys
import time
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))


# ---------------------------------------------------------------------------
# axioms, written out again from the definitions in Section 2 of the paper
# ---------------------------------------------------------------------------

def associative_hyper(t, n):
    for i in range(n):
        for j in range(n):
            tij = t[i][j]
            for k in range(n):
                l = r = 0
                for s in range(n):
                    if tij >> s & 1:
                        l |= t[s][k]
                for s in range(n):
                    if t[j][k] >> s & 1:
                        r |= t[i][s]
                if l != r:
                    return False
    return True


def reversible(t, n, inv):
    for x in range(n):
        for y in range(n):
            for z in range(n):
                if t[y][z] >> x & 1:
                    if not (t[x][inv[z]] >> y & 1):
                        return False
                    if not (t[inv[y]][x] >> z & 1):
                        return False
    return True


def partial_ok(t, n):
    """associativity on triples whose entries are all already determined"""
    for i in range(n):
        for j in range(n):
            if not t[i][j]:
                continue
            for k in range(n):
                if not t[j][k]:
                    continue
                ok = True
                for s in range(n):
                    if (t[i][j] >> s & 1) and not t[s][k]:
                        ok = False
                        break
                if ok:
                    for s in range(n):
                        if (t[j][k] >> s & 1) and not t[i][s]:
                            ok = False
                            break
                if not ok:
                    continue
                l = r = 0
                for s in range(n):
                    if t[i][j] >> s & 1:
                        l |= t[s][k]
                for s in range(n):
                    if t[j][k] >> s & 1:
                        r |= t[i][s]
                if l != r:
                    return False
    return True


def involutions(n):
    """involutions of {1, ..., n-1}, as full maps on {0, ..., n-1}"""
    pts = list(range(1, n))
    out = []

    def rec(rem, cur):
        if not rem:
            mp = list(range(n))
            for a, b in cur:
                mp[a], mp[b] = b, a
            out.append(mp)
            return
        x = rem[0]
        rec(rem[1:], cur)                       # x is self-inverse
        for i in range(1, len(rem)):            # x paired with rem[i]
            y = rem[i]
            rec(rem[1:i] + rem[i + 1:], cur + [(x, y)])

    rec(pts, [])
    return out


def enumerate_polygroups(n):
    """all labelled polygroups on {0..n-1} with 0 a scalar identity"""
    cells = [(i, j) for i in range(1, n) for j in range(1, n)]
    full = (1 << n) - 1
    out = []
    for inv in involutions(n):
        t = [[0] * n for _ in range(n)]
        for x in range(n):
            t[0][x] = 1 << x
            t[x][0] = 1 << x

        def rec(k):
            if k == len(cells):
                if associative_hyper(t, n) and reversible(t, n, inv):
                    # reproduction, checked rather than assumed
                    for x in range(n):
                        row = col = 0
                        for y in range(n):
                            row |= t[x][y]
                            col |= t[y][x]
                        if row != full or col != full:
                            return
                    out.append([r[:] for r in t])
                return
            i, j = cells[k]
            ebit = 1 if j == inv[i] else 0
            for mask in range(1 << (n - 1)):
                s = (mask << 1) | ebit
                if not s:
                    continue
                t[i][j] = s
                if partial_ok(t, n):
                    rec(k + 1)
            t[i][j] = 0

        rec(0)
    return out


def enumerate_semigroups(n):
    """all labelled semigroups on {0..n-1} with x.0 = 0 for every x"""
    cells = [(i, j) for i in range(n) for j in range(1, n)]
    out = []
    mt = [[0] * n for _ in range(n)]

    def rec(k):
        if k == len(cells):
            for i in range(n):
                for j in range(n):
                    ij = mt[i][j]
                    for l in range(n):
                        if mt[ij][l] != mt[i][mt[j][l]]:
                            return
            out.append([r[:] for r in mt])
            return
        i, j = cells[k]
        for v in range(n):
            mt[i][j] = v
            # prune on associativity among already-determined triples
            bad = False
            for a in range(n):
                for b in range(n):
                    for c in range(n):
                        if (a, b) > (i, j) or (b, c) > (i, j):
                            continue
                        ab, bc = mt[a][b], mt[b][c]
                        if (ab, c) > (i, j) or (a, bc) > (i, j):
                            continue
                        if mt[ab][c] != mt[a][bc]:
                            bad = True
                            break
                    if bad:
                        break
                if bad:
                    break
            if not bad:
                rec(k + 1)
        mt[i][j] = 0

    rec(0)
    return out


def left_distributive(t, mt, n, img):
    for a in range(n):
        ia = img[a]
        ma = mt[a]
        for b in range(n):
            mab = ma[b]
            for c in range(n):
                if ia[t[b][c]] != t[mab][ma[c]]:
                    return False
    return True


def right_distributive(t, mt, n):
    for a in range(n):
        for b in range(n):
            for c in range(n):
                l = 0
                for s in range(n):
                    if t[b][c] >> s & 1:
                        l |= 1 << mt[s][a]
                if l != t[mt[b][a]][mt[c][a]]:
                    return False
    return True


def make_img(mt, n):
    """img[a][S] = union over s in S of {a.s}, as a bitmask"""
    img = []
    for a in range(n):
        row = [0] * (1 << n)
        for S in range(1 << n):
            v = 0
            for s in range(n):
                if S >> s & 1:
                    v |= 1 << mt[a][s]
            row[S] = v
        img.append(row)
    return img


# ---------------------------------------------------------------------------
# isomorphism
# ---------------------------------------------------------------------------

def perms(n):
    return [(0,) + p for p in itertools.permutations(range(1, n))]


def permsub(s, p, n):
    r = 0
    for i in range(n):
        if s >> i & 1:
            r |= 1 << p[i]
    return r


def code_pg(t, n):
    return "".join("%x" % t[i][j] for i in range(1, n) for j in range(1, n))


def code_sg(mt, n):
    return "".join("%x" % mt[i][j] for i in range(n) for j in range(1, n))


def apply_pg(t, p, n):
    nt = [[0] * n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            nt[p[i]][p[j]] = permsub(t[i][j], p, n)
    return nt


def apply_sg(mt, p, n):
    nm = [[0] * n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            nm[p[i]][p[j]] = p[mt[i][j]]
    return nm


def canon_pg(t, n, P):
    return min(code_pg(apply_pg(t, p, n), n) for p in P)


def canon_sg(mt, n, P):
    return min(code_sg(apply_sg(mt, p, n), n) for p in P)


def canon_pair(t, mt, n, P):
    best = None
    for p in P:
        c = code_pg(apply_pg(t, p, n), n) + "|" + code_sg(apply_sg(mt, p, n), n)
        if best is None or c < best:
            best = c
    return best


# ---------------------------------------------------------------------------

def load(name, n, field=None):
    path = os.path.join(HERE, "data", f"{name}_n{n}.csv")
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return list(csv.DictReader(f))


def run(n):
    P = perms(n)
    fac = len(P)
    fails = []

    def need(cond, msg):
        if not cond:
            fails.append(msg)

    print(f"\n================  order n = {n}  ================")

    t0 = time.time()
    pgs = enumerate_polygroups(n)
    print(f"  polygroups      : {len(pgs):>6} labelled   ({time.time()-t0:.1f}s)")
    t0 = time.time()
    sgs = enumerate_semigroups(n)
    print(f"  semigroups      : {len(sgs):>6} labelled   ({time.time()-t0:.1f}s)")

    t0 = time.time()
    imgs = [make_img(mt, n) for mt in sgs]
    hnr, hr, kr = [], [], []
    for t in pgs:
        add_comm = all(t[x][y] == t[y][x] for x in range(n) for y in range(n))
        for mt, img in zip(sgs, imgs):
            if not left_distributive(t, mt, n, img):
                continue
            hnr.append((t, mt))
            if all(mt[0][x] == 0 and mt[x][0] == 0 for x in range(n)) \
                    and right_distributive(t, mt, n):
                hr.append((t, mt))
                if add_comm:
                    kr.append((t, mt))
    print(f"  hypernearrings  : {len(hnr):>6} labelled   ({time.time()-t0:.1f}s)")
    print(f"  hyperrings      : {len(hr):>6} labelled")
    print(f"  Krasner         : {len(kr):>6} labelled")

    # ---- isomorphism classes, computed here from scratch -----------------
    t0 = time.time()
    cls_pg = {canon_pg(t, n, P) for t in pgs}
    cls_sg = {canon_sg(mt, n, P) for mt in sgs}
    cls_hnr = {canon_pair(t, mt, n, P) for t, mt in hnr}
    cls_hr = {canon_pair(t, mt, n, P) for t, mt in hr}
    cls_kr = {canon_pair(t, mt, n, P) for t, mt in kr}
    print(f"  classes         : {len(cls_pg)} / {len(cls_sg)} / {len(cls_hnr)} / "
          f"{len(cls_hr)} / {len(cls_kr)}   ({time.time()-t0:.1f}s)")

    # ---- compare with the published files, in both directions ------------
    def compare(name, mine, rows, key):
        if rows is None:
            print(f"    {name:<22}: no file, skipped")
            return
        theirs = {key(r) for r in rows}
        need(len(theirs) == len(rows), f"{name}: duplicate entries in the file")
        missing = mine - theirs      # we found it, the file does not list it
        extra = theirs - mine        # the file lists it, we did not find it
        need(not missing, f"{name}: {len(missing)} class(es) MISSING from the "
                          f"published list, e.g. {sorted(missing)[:3]}")
        need(not extra, f"{name}: {len(extra)} class(es) in the published list "
                        f"that this enumeration does not produce, e.g. {sorted(extra)[:3]}")
        mark = "OK" if not missing and not extra else "MISMATCH"
        print(f"    {name:<22}: {len(mine):>4} classes, file has {len(theirs):>4}  [{mark}]")

    compare("polygroups", cls_pg, load("polygroups", n),
            lambda r: r["code"])
    compare("semigroups", cls_sg, load("semigroups", n),
            lambda r: r["code"])
    compare("hypernearrings", cls_hnr, load("hypernearrings", n),
            lambda r: r["add_code"] + "|" + r["mult_code"])
    compare("hyperrings", cls_hr, load("hyperrings", n),
            lambda r: r["add_code"] + "|" + r["mult_code"])
    compare("Krasner hyperrings", cls_kr, load("krasner_hyperrings", n),
            lambda r: r["add_code"] + "|" + r["mult_code"])

    # ---- labelled totals against the orbit-stabiliser identity -----------
    for name, labelled, rows in (
            ("polygroups", len(pgs), load("polygroups", n)),
            ("semigroups", len(sgs), load("semigroups", n)),
            ("hypernearrings", len(hnr), load("hypernearrings", n)),
            ("hyperrings", len(hr), load("hyperrings", n)),
            ("Krasner hyperrings", len(kr), load("krasner_hyperrings", n))):
        if rows is None:
            continue
        s = sum(fac // int(r["aut_order"]) for r in rows)
        need(s == labelled,
             f"{name}: sum of {fac}/|Aut| over the file is {s}, "
             f"but this enumeration finds {labelled} labelled structures")

    # ---- re-prove Lemma 3.1 on everything we generated --------------------
    bad = 0
    for t in pgs:
        inv = [None] * n
        for x in range(n):
            cand = [y for y in range(n) if (t[x][y] & 1) and (t[y][x] & 1)]
            if len(cand) != 1:
                bad += 1
                break
            inv[x] = cand[0]
        else:
            for x in range(n):
                for y in range(n):
                    if bool(t[x][y] & 1) != (y == inv[x]):
                        bad += 1
    need(bad == 0, f"Lemma 3.1 fails on {bad} generated polygroups")
    print(f"    Lemma 3.1 holds on all {len(pgs)} generated polygroups")

    return fails


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--order", type=int, choices=(3, 4), default=None)
    args = ap.parse_args()
    orders = (args.order,) if args.order else (3, 4)
    fails = []
    for n in orders:
        fails += run(n)
    print("\n" + "=" * 50)
    if fails:
        print(f"FAILED: {len(fails)} check(s) did not pass\n")
        for f in fails:
            print("  -", f)
        sys.exit(1)
    print("ALL CHECKS PASSED")
    print("The published lists are both correct and complete.")
    sys.exit(0)


if __name__ == "__main__":
    main()
